version: "3"
services:

  cms-lb:
    image: cms-lb
    build: loadbalancer
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 30s
    dns:
      - 8.8.8.8
      - 9.9.9.9
    ports:
      - "${LBPORT}:80"
    depends_on:
      - "cms-fe"
      - "cms-api"
      - "cms-admin"
    networks:
      - cmsnetwork

  cms-fe:
    image: cms-fe
    build: frontend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 30s
    environment:
      - DOMAIN=${DOMAIN}
      - API_INT=${API_INT}
    dns:
      - 8.8.8.8
      - 9.9.9.9
    # ports:
    #   - "8080:8080"
    networks:
      - cmsnetwork

  cms-admin:
    image: cms-admin
    build: admin
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 30s
    environment:
      - DOMAIN=${DOMAIN}
      - API_INT=${API_INT}
      - API_PUB=${API_PUB}
      - API_EXT=${API_EXT}
    dns:
      - 8.8.8.8
      - 9.9.9.9
    # ports:
    #   - "8082:8081"
    networks:
      - cmsnetwork

  cms-api:
    image: cms-api
    build: api
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 30s    
    environment:
      - DOMAIN=${DOMAIN}
      - SLACKHOOK=${SLACKHOOK}
      - API_PORT=${API_PORT}
    dns:
      - 8.8.8.8
      - 9.9.9.9
    # ports:
    #   - "4006:4006"
    volumes:
      - ./data:/app/data
      - ./meta:/app/meta
      - ./pages:/app/pages
      - ./backups:/app/backups
    networks:
      - cmsnetwork

networks:
  cmsnetwork:
