version: "3"
services:

  cms-web:
    image: cms-web
    build: webserver
    ports:
      - "8888:80"
    networks:
      - cmsnetwork

  cms-fe:
    image: cms-fe
    build: frontend
    ports:
      - "8080:80"
    networks:
      - cmsnetwork

  cms-admin:
    image: cms-admin
    build: admin
    ports:
      - "8082:81"
    networks:
      - cmsnetwork

  cms-api:
    image: cms:1.0
    build: .
    ports:
      - "4006:4006"
    volumes:
      - ./data:/app/data
      - ./meta:/app/meta
      - ./pages:/app/pages
    networks:
      - cmsnetwork

networks:
  cmsnetwork:
