version: "3"
services:

  cms-lb:
    image: cms-lb
    build: loadbalancer
    ports:
      - "${LBPORT}:80"
    networks:
      - cmsnetwork

  cms-fe:
    image: cms-fe
    build: frontend
    environment:
      - DOMAIN=${DOMAIN}
      - API_INT=${API_INT}
    ports:
      - "8080:8080"
    networks:
      - cmsnetwork

  cms-admin:
    image: cms-admin
    build: admin
    environment:
      - DOMAIN=${DOMAIN}
      - API_INT=${API_INT}
      - API_PUB=${API_PUB}
      - API_EXT=${API_EXT}
    ports:
      - "8082:8081"
    networks:
      - cmsnetwork

  cms-api:
    image: cms-api
    build: api
    environment:
      - SLACKHOOK=${SLACKHOOK}
      - API_PORT=${API_PORT}
    dns:
      - 8.8.8.8
      - 9.9.9.9
    ports:
      - "4006:4006"
    volumes:
      - ./data:/app/data
      - ./meta:/app/meta
      - ./pages:/app/pages
      - ./backups:/app/backups
    networks:
      - cmsnetwork

networks:
  cmsnetwork:
